shared:
  node_container: &node_container
    language: node_js
    node_js:
      - 8.10.0
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - export PATH="$HOME/.yarn/bin:$PATH"
    install:
      - yarn install --production=false --frozen-lockfile
    cache: yarn

matrix:
  include:
    - <<: *node_container
      name: 'Node - build, type-check, and end-to-end tests'
      script:
        - yarn build
        - yarn test --testPathPattern react-server-webpack-plugin
    - <<: *node_container
      name: 'Node - unit tests'
      script:
        - yarn test --testPathIgnorePatterns react-server-webpack-plugin
        - yarn codecov
    - <<: *node_container
      name: 'Node - lint'
      script:
        - yarn lint
        - yarn ci:lint-docs
    - language: ruby
      before_install:
        - cd gems/quilt_rails
        - gem install bundler
      install:
        - bundle install
      script:
        - bundle exec rake test
notifications:
  slack:
    on_pull_requests: false
    secure:
      1dRk1kc3vEav6ut7FG5hj8Gowx99B/M4hEXf0b9RDHGEhaWVoDbDGZEqGUn1fdltPLNPmlGp4tM9b00ISu1MMflYkJl3l/8Czp/xGSbzD7FZYACJB2IujHms1xhIijSFkD5+EG3hcwmleWqvySjSQ42z5saaNHlM/mO5kUMIuTgaqqQV2wZC8mN0eZva85Y8HzYIeT0a5DvrTOupUiXKxk8M+y5k9HCuRYTLbgDcdjRR0u0RbGak6PVRFlSEBV4hEjdKS1aQyjXutKWfZxdgWiQbpdC0RmTNTePN0p53pt7oPFHv+BSN7eWzLkeMquIu02r2EEAb9tnYRpChuuFOphguSI5BDYtS1/zOx+VZhkXzoo4nq5iEbh8vYEXI+mj5op9Lz+v38I9j3haCjzjz/PeI7W8/DUIPHhO3t9fqKXqySm/2bx0ZSdSyW8Em63v+8LudkxEcBVLtn1ZPvOCOCfRt+FvzlwJZThzTJ92efxPuFiL5AZoeU4RQGpV/3A7W/wnHt830nNgiUAjMMXhuznF1Fnn4rsGh+Ntr8m18P0DUx+XPflp/r1EfPnkapwSM02tUwF3xunT6i++xg8tuTcVOjWLmq3CBgZ+Q/7g3Ff6Ykcfupqgm5bDgzkQ9bNZM/jAN0cDavzK9i0AELqZkqFcrQclEarL9NgAeCvsl0yk=
