org_line: Shopify Core
owners:
  - Shopify/web-foundation
  - tzvipm
  - TheMallen
audience: partner
classification: library
ci_url: https://travis-ci.org/Shopify/quilt
slack_channels:
  - kernel-web-foundations
