name: Ruby-CI

on:
  pull_request: ~
  push:
    branches: [main]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest
    name: 'Test (Ruby ${{ matrix.ruby-version }})'
    strategy:
      matrix:
        ruby-version: ['3.1']

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: ruby/setup-ruby@v1
        name: Use Ruby ${{ matrix.ruby-version }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: ğŸ“¦ Install dependencies
        run: |
          bundle config set ignore_messages true
          bundle install --frozen
        working-directory: ./gems/quilt_rails

      - name: ğŸ’…ğŸ¼ Lint
        run: bundle exec rubocop
        working-directory: ./gems/quilt_rails

      - name: Test
        run: bundle exec rake test
        working-directory: ./gems/quilt_rails
